POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pcmthIiwiaWQiOiI2MWIzNWI0NWVjNjQyZGNkNWQ1Yzk0MGIiLCJpYXQiOjE2MzkxNDQzNTl9.IOo3AX-wsTweCG_xK91jbdLjQcV1bgNqb5HIwqIpSjg

{
    "title": "Keskimäärin likejä",
    "author": "waaa",
    "url": "urli",
    "likes": 5
}