DELETE http://localhost:3003/api/blogs/61b34cb1d140fbbfe3a4b528
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpaXJhIiwiaWQiOiI2MWIzNTBmMDAzMjVkM2E1ZDdiODBlZDQiLCJpYXQiOjE2MzkxNDI4NDd9.1UTj5cMkYJ4wS4E6Xicqk5yfmUQg9ulfoYWq49BPvNI